const weatherCodes = [
    { code: 0, description: "Clear sky" },
    { code: 1, description: "Mainly clear" },
    { code: 2, description: "Partly cloudy" },
    { code: 3, description: "Overcast" },
    { code: 45, description: "Fog" },
    { code: 48, description: "Rime fog" },
    { code: 51, description: "Light drizzle" },
    { code: 53, description: "Moderate drizzle" },
    { code: 55, description: "Heavy drizzle" },
    { code: 56, description: "Light freezing drizzle" },
    { code: 57, description: "Heavy freezing drizzle" },
    { code: 61, description: "Light rain" },
    { code: 63, description: "Moderate rain" },
    { code: 65, description: "Heavy rain" },
    { code: 66, description: "Light freezing rain" },
    { code: 67, description: "Heavy freezing rain" },
    { code: 71, description: "Light snowfall" },
    { code: 73, description: "Moderate snowfall" },
    { code: 75, description: "Heavy snowfall" },
    { code: 77, description: "Snow grains" },
    { code: 80, description: "Light rain showers" },
    { code: 81, description: "Moderate rain showers" },
    { code: 82, description: "Heavy rain showers" },
    { code: 85, description: "Light snow showers" },
    { code: 86, description: "Heavy snow showers" },
    { code: 95, description: "Thunderstorm" },
    { code: 96, description: "Thunderstorm with light hail" },
    { code: 99, description: "Thunderstorm with heavy hail" },
];
