

export const static_icons = [
    { code: 0, day: require('../assets/icons/static_icons/day.svg'), night: require('../assets/icons/static_icons/night.svg')},
    { code: 1, day: require('../assets/icons/static_icons/cloudy-day-1.svg'), night: require('../assets/icons/static_icons/cloudy-night-1.svg')},
    { code: 2, day: require('../assets/icons/static_icons/cloudy-day-2.svg'), night: require('../assets/icons/static_icons/cloudy-night-2.svg')},
    { code: 3, day: require('../assets/icons/static_icons/cloudy-day-3.svg'), night: require('../assets/icons/static_icons/cloudy-night-3.svg')},
    { code: 45, day: require('../assets/icons/static_icons/cloudy-day-3.svg'), night: require('../assets/icons/static_icons/cloudy-night-3.svg')},
    { code: 48, day: require('../assets/icons/static_icons/cloudy-day-3.svg'), night: require('../assets/icons/static_icons/cloudy-night-3.svg')},
    { code: 51, day: require('../assets/icons/static_icons/rainy-1.svg'), night: require('../assets/icons/static_icons/rainy-4.svg')},
    { code: 53, day: require('../assets/icons/static_icons/rainy-2.svg'), night: require('../assets/icons/static_icons/rainy-5.svg')},
    { code: 55, day: require('../assets/icons/static_icons/rainy-3.svg'), night: require('../assets/icons/static_icons/rainy-6.svg')},
    { code: 56, day: require('../assets/icons/static_icons/rainy-7.svg'), night: require('../assets/icons/static_icons/rainy-7.svg')},
    { code: 57, day: require('../assets/icons/static_icons/rainy-7.svg'), night: require('../assets/icons/static_icons/rainy-7.svg')},
    { code: 61, day: require('../assets/icons/static_icons/rainy-4.svg'), night: require('../assets/icons/static_icons/rainy-4.svg')},
    { code: 63, day: require('../assets/icons/static_icons/rainy-5.svg'), night: require('../assets/icons/static_icons/rainy-5.svg')},
    { code: 65, day: require('../assets/icons/static_icons/rainy-6.svg'), night: require('../assets/icons/static_icons/rainy-6.svg')},
    { code: 66, day: require('../assets/icons/static_icons/rainy-7.svg'), night: require('../assets/icons/static_icons/rainy-7.svg')},
    { code: 67, day: require('../assets/icons/static_icons/rainy-7.svg'), night: require('../assets/icons/static_icons/rainy-7.svg')},
    { code: 71, day: require('../assets/icons/static_icons/snowy-1.svg'), night: require('../assets/icons/static_icons/snowy-4.svg')},
    { code: 73, day: require('../assets/icons/static_icons/snowy-2.svg'), night: require('../assets/icons/static_icons/snowy-5.svg')},
    { code: 75, day: require('../assets/icons/static_icons/snowy-3.svg'), night: require('../assets/icons/static_icons/snowy-6.svg')},
    { code: 77, day: require('../assets/icons/static_icons/snowy-6.svg'), night: require('../assets/icons/static_icons/snowy-6.svg')},
    { code: 80, day: require('../assets/icons/static_icons/rainy-4.svg'), night: require('../assets/icons/static_icons/rainy-4.svg')},
    { code: 81, day: require('../assets/icons/static_icons/rainy-5.svg'), night: require('../assets/icons/static_icons/rainy-5.svg')},
    { code: 82, day: require('../assets/icons/static_icons/rainy-6.svg'), night: require('../assets/icons/static_icons/rainy-6.svg')},
    { code: 85, day: require('../assets/icons/static_icons/snowy-5.svg'), night: require('../assets/icons/static_icons/snowy-5.svg')},
    { code: 86, day: require('../assets/icons/static_icons/snowy-6.svg'), night: require('../assets/icons/static_icons/snowy-6.svg')},
    { code: 95, day: require('../assets/icons/static_icons/thunder.svg'), night: require('../assets/icons/static_icons/thunder.svg')},
    { code: 96, day: require('../assets/icons/static_icons/thunder.svg'), night: require('../assets/icons/static_icons/thunder.svg')},
    { code: 99, day: require('../assets/icons/static_icons/thunder.svg'), night: require('../assets/icons/static_icons/thunder.svg')},
];
